Device: cuda:0
Building server's model...
Preparing data...
Prepare 1 ...
Prepare 2 ...
Prepare 3 ...
Prepare 4 ...
Prepare 5 ...
Source domain (for training) is ['1', '2', '3', '4', '5']
Target domain (for testing) is ['0']
/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.10/site-packages/torchvision/models/_utils.py:252: UserWarning: Accessing the model URLs via the internal dictionary of the module is deprecated since 0.13 and may be removed in the future. Please access them via the appropriate Weights Enum instead.
  warnings.warn(
Saving to /home/ubuntu/long.ht/CCST/utils/../logs/../checkpoint/pacs/fedavg_no_fusion_no_DG_resnet50_locIter1/Target_0_seed_1/iters500_bs64_lr0.001_class345_817
=============Global iter is 0 ===============
----------------Training----------------
== Train epoch 0 ===
 1          | Train Loss: 5.6689
 1          | Train Class Acc: 0.0159
 5          | Train Loss: 5.6582
 5          | Train Class Acc: 0.0219
 2          | Train Loss: 5.5372
 2          | Train Class Acc: 0.0455
 3          | Train Loss: 5.6720
 3          | Train Class Acc: 0.0394
 4          | Train Loss: 5.0797
 4          | Train Class Acc: 0.2054
----------------Validate global model on source domains----------------
Traceback (most recent call last):
  File "/home/ubuntu/long.ht/CCST/./federated/fed_run.py", line 731, in <module>
    val_loss, val_acc = test(server_model, val_loader, loss_fun, device, args)
  File "/home/ubuntu/long.ht/CCST/./federated/fed_run.py", line 250, in test
    class_logit = model(data)
  File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/long.ht/CCST/nets/resnet.py", line 191, in forward
    return self.class_classifier(x)
  File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`